spring:
  application.name: user-profile-service
  dataSource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:${DB_PORT:3307}/${DB_NAME:user_profile}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
  # use JWT because using keycloak as OIDC, and it only natively support JWT
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_K8S_SERVICE_URI:http://keycloak.local:8081}/realms/${APP_REALM:showcase}
keycloak:
  admin:
    server-url: ${AUTH_SERVER_K8S_SERVICE_URI:http://keycloak.local:8081}
    realm: ${APP_REALM:showcase}
    client-id: admin-cli
    client-secret: ${KEYCLOAK_REALM_ADMIN_SECRET:J3U8O905QoJS3hdq8a0eS0aDKjim9LS5}
  target-realm: showcase