spring:
  application.name: casa-service
  dataSource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:3307/${DB_NAME:casa_db}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
  flyway:
    enabled: true
    locations: classpath:db/migration
  # use JWT because using keycloak as OIDC, and it only natively support JWT
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISS_URI:http://keycloak.local:8081/realms/showcase}

logging:
  level:
    root: debug
    sun: INFO
    javax.management: INFO

management:
  server.port: 9090
  endpoint:
    health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true