# base-service-chart/values.yaml
service:
  name: app
  image:
    repository: showcase
    name: app
    tag: v1.0
    pullPolicy: Never
  app:
    port: 8080
    replicas: 1
    portName: app-port
    protocol: TCP
  healthCheck:
    enabled: true
    port: 9090
    portName: actuator-port
    protocol: TCP
    paths:
      readiness: /actuator/health/readiness
      liveness: /actuator/health/liveness

config:
  db:
    hostname: "host.docker.internal"
    port: "3307"
    name: ""
    username: ""
    password: ""

autoscaling:
  enabled: false

serviceAccount:
  create: false

ingress:
  enabled: true
  className: ""
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: "{{ .Values.service.name }}.local"
      paths:
        - path: /
          pathType: Prefix