# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.service.replicas }}
  selector:
    matchLabels:
      {{- include "base-service-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "base-service-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: "{{ .Values.service.image.repository }}/{{ .Values.service.image.name }}:{{ .Values.service.image.tag }}"
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          # Provide info on what port would be exposed, real expose config is in Service yaml
          ports:
            - name: {{ .Values.service.app.portName }}
              containerPort: {{ .Values.service.app.port }}
              protocol: {{ .Values.service.app.protocol}}
          {{- if .Values.service.healthCheck.enabled }}
            - name: {{ .Values.service.healthCheck.portName }}
              containerPort: {{ .Values.service.healthCheck.port }}
              protocol: {{ .Values.service.healthCheck.protocol}}
          {{- end }}

          env:
          {{- range $key, $value := .Values.config.db }}
          - name: DB_{{ $key | upper }}
            valueFrom:
              configMapKeyRef:
                name: {{ $.Values.service.name }}-config
                key: DB_{{ $key | upper }}
          {{- end }}
          {{- if .Values.service.healthCheck.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.service.healthCheck.paths.readiness }}
              port: {{ .Values.service.healthCheck.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.service.healthCheck.paths.liveness }}
              port: {{ .Values.service.healthCheck.port }}
          {{- end }}